name: Comment on P1 issues

on:
  issues:
    types:
      - labeled

jobs:
  add-comment:
    if: github.event.label.name == 'P1'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:            
      - name: Add comment
        uses: actions/github-script@v6.3.3
        id: get-assignees
        with:
          script: |
            const msg = ':warning: Refrain from assigning this issue to yourself if you have another P1 issue assigned that is not yet closed.'
            const createCommentOptions = {
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            }
            
            const result = await github.rest.issues.get({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            
            const { assignees } = result.data
            if (assignees.length == 0) {
              await github.rest.issues.createComment({
                ...createCommentOptions,
                body: '**' + msg + '**',
              })
              return
            }
            
            const assignees_tagged = assignees.map((user) => '@' + user.login).join(' ')
            await github.rest.issues.createComment({
              ...createCommentOptions,
              body: assignees_tagged + ' ' + msg + '\nKindly acknowledge this message by commenting "Acknowledged".',
            })
            
            
